module CommandId
  READ_ATTRIBUTES = 0x00
  READ_ATTRIBUTES_RESPONSE = 0x01
  WRITE_ATTRIBUTES = 0x02
  WRITE_ATTRIBUTES_UNDEVIDED = 0x03
  WRITE_ATTRIBUTES_RESPONSE = 0x04
  WRITE_ATTRIBUTES_NO_RESPONSE = 0x05
  CONFIGURE_REPORTING = 0x06
  CONFIGURE_REPORTING_RESPONSE = 0x07
  READ_REPORTING_CONFIGURATION = 0x08
  READ_REPORTING_CONFIGURATION_RESPONSE = 0x09
  REPORT_ATTRIBUTES = 0x0a
  DEFAULT_RESPONSE = 0x0b
  DISCOVER_ATTRIBUTES = 0x0c
  DISCOVER_ATTRIBUTES_RESPONSE = 0x0d
  READ_ATTRIBUTES_STRUCTURED = 0x0e
  WRITE_ATTRIBUTES_STRUCTURED = 0x0f
  WRITE_ATTRIBUTES_STRUCTURED_RESPONSE = 0x10
  DISCOVER_COMMANDS_RECEIVED = 0x11
  DISCOVER_COMMANDS_RECEIVED_RESPONSE = 0x12
  DISCOVER_COMMANDS_GENERATED = 0x13
  DISCOVER_COMMANDS_GENERATED_RESPONSE = 0x14
  DISCOVER_ATTRIBUTES_EXTENDED = 0x15
  DISCOVER_ATTRIBUTES_EXTENDED_RESPONSE = 0x16
end
