class ZigbeeZDO
  CLUSTERS = {
    name: "Zigbee Device Profile",
      clusters: {
        0x0000 => "Network (16-bit) Address Request",
        0x8000 => "Network (16-bit) Address Response",
        0x0001 => "IEEE (64-bit) Address Request",
        0x8001 => "IEEE (64-bit) Address Response",
        0x0002 => "Node Descriptor Request",
        0x8002 => "Node Descriptor Response",
        0x0003 => "Power Descriptor Request",
        0x8003 => "Power Descriptor Response",
        0x0004 => "Simple Descriptor Request",
        0x8004 => "Simple Descriptor Response",
        0x0005 => "Active Endpoints Request",
        0x8005 => "Active Endpoints Response",
        0x0006 => "Match Descriptor Request",
        0x8006 => "Match Descriptor Response",
        0x0010 => "Complex Descriptor Request",
        0x8010 => "Complex Descriptor Response",
        0x0011 => "User Descriptor Request",
        0x8011 => "User Descriptor Response",
        0x0012 => "Discovery Cache Request",
        0x8012 => "Discovery Cache Response",
        0x0013 => "Device Annoucement",
        0x0014 => "User Descriptor Set",
        0x0015 => "System Server Discovery Request",
        0x8015 => "System Server Discovery Response",
        0x0016 => "Discovery Store Request",
        0x8016 => "Discovery Store Response",
        0x0017 => "Node Discovery Store Request",
        0x8017 => "Node Discovery Store Response",
        0x0018 => "Power Descriptor Store Request",
        0x8018 => "Power Descriptor Store Response",
        0x0030 => "Management Network Discovery Request",
        0x8030 => "Management Network Discovery Response",
        0x0031 => "Management LQI (Neighbor Table) Request",
        0x8031 => "Management LQI (Neighbor Table) Response",
        0x0032 => "Management Rtg (Routing Table) Request",
        0x8032 => "Management Rtg (Routing Table) Response",
        0x0034 => "Management Leave Request",
        0x8034 => "Management Leave Response",
        0x0036 => "Management Permit Join Request",
        0x8036 => "Management Permit Join Response",
        0x0038 => "Management Network Update Request",
        0x8038 => "Management Network Update Notify",
    }
  }
end
